name: quant_rl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.1
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.12.12
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - beautifulsoup4==4.14.3
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - curl-cffi==0.13.0
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - filelock==3.20.1
      - fonttools==4.61.1
      - frozendict==2.4.7
      - fsspec==2025.12.0
      - grpcio==1.76.0
      - gymnasium==1.2.2
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multitasking==0.0.12
      - networkx==3.6.1
      - numpy==2.3.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==2.3.3
      - peewee==3.18.3
      - pillow==12.0.0
      - platformdirs==4.5.1
      - protobuf==6.33.2
      - pycparser==2.23
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - six==1.17.0
      - soupsieve==2.8
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torch==2.9.1
      - triton==3.5.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.6.0
      - websockets==15.0.1
      - werkzeug==3.1.4
      - yfinance==0.2.66
prefix: /home/yejun/miniconda3/envs/quant_rl
